from django.db import models

# Create your models here, evan.

class PropDetail(models.Model):
    acres = models.DecimalField(decimal_places=3, max_digits=9, verbose_name='Acres')
    acresbottomland = models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Acres of Bottom Land')
    agexemption = models.CharField(max_length=3, verbose_name='Age Exemption')
    assumption = models.CharField(max_length=579, verbose_name='Assumption')
    backonmarketdate = models.DateTimeField(verbose_name='Back on Market Date')
    barn1length = models.IntegerField(verbose_name='Barn 1 Length')
    barn1width = models.IntegerField(verbose_name='Barn 1 Width')
    barn2length = models.IntegerField(verbose_name='Barn 2 Length')
    barn2width = models.IntegerField(verbose_name='Barn 2 Width')
    barn3length = models.IntegerField(verbose_name='Barn 3 Length')
    barn3width = models.IntegerField(verbose_name='Barn 3 Width')
    barndesc = models.CharField(max_length=765, verbose_name='Barn Description')
    roombed2length = models.IntegerField(verbose_name='Bedroom 2 Length')
    roombed2level = models.CharField(max_length=3, verbose_name='Bedroom 2 Level')
    roombed2width = models.IntegerField(verbose_name='Bedroom 2 Width')
    roombed3length = models.IntegerField(verbose_name='Bedroom 3 Length')
    roombed3level = models.CharField(max_length=3, verbose_name='Bedroom 3 Level')
    roombed3width = models.IntegerField(verbose_name='Bedroom 3 Width')
    roombed4length = models.IntegerField(verbose_name='Bedroom 4 Length')
    roombed4level = models.CharField(max_length=3, verbose_name='Bedroom 4 Level')
    roombed4width = models.IntegerField(verbose_name='Bedroom 4 Width')
    roombed5length = models.IntegerField(verbose_name='Bedroom 5 Length')
    roombed5level = models.CharField(max_length=3, verbose_name='Bedroom 5 Level')
    roombed5width = models.IntegerField(verbose_name='Bedroom 5 Width')
    beds = models.IntegerField(verbose_name='Bedrooms')
    block = models.CharField(max_length=21, verbose_name='Block')
    roombreakfastlength = models.IntegerField(verbose_name='Breakfast Room Length')
    roombreakfastlevel = models.CharField(max_length=3, verbose_name='Breakfast Room Level')
    roombreakfastwidth = models.IntegerField(verbose_name='Breakfast Room Width')
    building = models.CharField(max_length=327, verbose_name='Building')
    buildingnum = models.CharField(max_length=15, verbose_name='Building Number')
    carportcap = models.IntegerField(verbose_name='Carport Spaces')
    city = models.CharField(max_length=96, verbose_name='City')
    closeddate = models.DateTimeField(verbose_name='Close Date')
    commonfeatures = models.CharField(max_length=858, verbose_name='Common Features')
    compbuy = models.CharField(max_length=30, verbose_name='Comp Buy')
    compsell = models.CharField(max_length=30, verbose_name='Comp Sell')
    complexname = models.CharField(max_length=75, verbose_name='Complex Name')
    contingencydate = models.DateTimeField(verbose_name='Contingency Date')
    county = models.CharField(max_length=96, verbose_name='County')
    crops = models.CharField(max_length=738, verbose_name='Crops')
    acrescultivated = models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Cultivated Acres')
    roomdininglength = models.IntegerField(verbose_name='Dining Room Length')
    roomdininglevel = models.CharField(max_length=3, verbose_name='Dining Room Level')
    roomdiningwidth = models.IntegerField(verbose_name='Dining Room Width')
    directions = models.CharField(max_length=450, verbose_name='Directions')
    easements = models.CharField(max_length=363, verbose_name='Easements')
    energy = models.CharField(max_length=507, verbose_name='Energy')
    equipment = models.CharField(max_length=837, verbose_name='Equipment')
    excludes = models.CharField(max_length=330, verbose_name='Excludes')
    exterior = models.CharField(max_length=765, verbose_name='Exterior')
    fence = models.CharField(max_length=519, verbose_name='Fence')
    financeproposed = models.CharField(max_length=450, verbose_name='Finance Proposed')
    financingapproved = models.CharField(max_length=75, verbose_name='Financing Approved')
    fireplacedesc = models.CharField(max_length=765, verbose_name='Fireplace Description')
    fireplaces = models.IntegerField(verbose_name='Fireplaces')
    floors = models.CharField(max_length=489, verbose_name='Floors')
    forlease = models.CharField(max_length=3, verbose_name='For Lease')
    foundation = models.CharField(max_length=282, verbose_name='Foundation')
    roadfrontage = models.IntegerField(verbose_name='Frontage Road')
    roadfrontagedesc = models.CharField(max_length=765, verbose_name='Frontage Road Description')
    bathsfull = models.IntegerField(verbose_name='Full Baths')
    bathsfullbasement = models.IntegerField(verbose_name='Full Baths (Basement)')
    bathsfulllevel1 = models.IntegerField(verbose_name='Full Baths (Lvl 1)')
    bathsfulllevel2 = models.IntegerField(verbose_name='Full Baths (Lvl 2)')
    bathsfulllevel3 = models.IntegerField(verbose_name='Full Baths (Lvl 3)')
    garagecap = models.IntegerField(verbose_name='Garage Capacity')
    garagedesc = models.CharField(max_length=765, verbose_name='Garage Description')
    roomgaragelength = models.IntegerField(verbose_name='Garage Length')
    roomgaragewidth = models.IntegerField(verbose_name='Garage Width')
    bathshalf = models.IntegerField(verbose_name='Half Baths')
    bathshalfbasement = models.IntegerField(verbose_name='Half Baths (Basement)')
    bathshalflevel1 = models.IntegerField(verbose_name='Half Baths (Lvl 1)')
    bathshalflevel2 = models.IntegerField(verbose_name='Half Baths (Lvl 2)')
    bathshalflevel3 = models.IntegerField(verbose_name='Half Baths (Lvl 3)')
    handicap = models.BooleanField(verbose_name='Handicap')
    handicapyn = models.BooleanField(verbose_name='Handicap')
    heatsystem = models.CharField(max_length=765, verbose_name='Heat System')
    assocfee = models.IntegerField(verbose_name='HOA Fee')
    assocfeeincludes = models.CharField(max_length=765, verbose_name='HOA Fee Includes')
    assocfeepaid = models.CharField(max_length=30, verbose_name='HOA Fee Paid')
    hoa = models.CharField(max_length=75, verbose_name='HOA Name')
    housingtype = models.CharField(max_length=765, verbose_name='Housing Type')
    interior = models.CharField(max_length=765, verbose_name='Interior')
    internetlist_all = models.CharField(max_length=450, verbose_name='Internetlist All')
    acresirrigated = models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Irrigated Acres')
    roomkitchendesc = models.CharField(max_length=408, verbose_name='Kitchen Description')
    roomkitchenlength = models.IntegerField(verbose_name='Kitchen Length')
    roomkitchenlevel = models.CharField(max_length=3, verbose_name='Kitchen Level')
    roomkitchenwidth = models.IntegerField(verbose_name='Kitchen Width')
    landlease = models.CharField(max_length=3, verbose_name='Land Lease')
    legal = models.CharField(max_length=90, verbose_name='Legal')
    lender = models.CharField(max_length=75, verbose_name='Lender')
    roomliving1length = models.IntegerField(verbose_name='Living Room 1 Length')
    roomliving1level = models.CharField(max_length=3, verbose_name='Living Room 1 Level')
    roomliving1width = models.IntegerField(verbose_name='Living Room 1 Width')
    roomliving2length = models.IntegerField(verbose_name='Living Room 2 Length')
    roomliving2level = models.CharField(max_length=3, verbose_name='Living Room 2 Level')
    roomliving2width = models.IntegerField(verbose_name='Living Room 2 Width')
    roomliving3length = models.IntegerField(verbose_name='Living Room 3 Length')
    roomliving3level = models.CharField(max_length=3, verbose_name='Living Room 3 Level')
    roomliving3width = models.IntegerField(verbose_name='Living Room 3 Width')
    loan1amount = models.DecimalField(decimal_places=2, max_digits=13, verbose_name='Loan 1 Amount')
    loan1interestrate = models.DecimalField(decimal_places=3, max_digits=7, verbose_name='Loan 1 Interest Rate')
    loan1years = models.IntegerField(verbose_name='Loan 1 Years')
    loan2amount = models.IntegerField(verbose_name='Loan 2 Amount')
    loan2financing = models.CharField(max_length=30, verbose_name='Loan 2 Financing')
    loan2interestrate = models.DecimalField(decimal_places=3, max_digits=7, verbose_name='Loan 2 Interest Rate')
    loan2mortgage = models.CharField(max_length=3, verbose_name='Loan 2 Mortgage')
    loan2years = models.IntegerField(verbose_name='Loan 2 Years')
    loanbalance = models.IntegerField(verbose_name='Loan Balance')
    loaninterestrate = models.DecimalField(decimal_places=4, max_digits=7, verbose_name='Loan Interest Rate')
    loanmortgagedate = models.DateTimeField(verbose_name='Loan Mortgage Date')
    loanpayment = models.IntegerField(verbose_name='Loan Payment')
    loanpaymenttype = models.CharField(max_length=75, verbose_name='Loan Payment Type')
    loantype = models.CharField(max_length=75, verbose_name='Loan Type')
    lotdesc = models.CharField(max_length=888, verbose_name='Lot Description')
    lotdim = models.CharField(max_length=75, verbose_name='Lot Dimensions')
    lotnum = models.CharField(max_length=15, verbose_name='Lot Number')
    lotsize = models.CharField(max_length=195, verbose_name='Lot Size')
    mapcoord = models.CharField(max_length=15, verbose_name='Map Coordinates')
    mappage = models.CharField(max_length=15, verbose_name='Map Page')
    mapbook = models.CharField(max_length=6, verbose_name='Mapbook')
    roombedbathdesc = models.CharField(max_length=765, verbose_name='Master Bath Description')
    roommasterbedlength = models.IntegerField(verbose_name='Master Bedroom Length')
    roommasterbedlevel = models.CharField(max_length=3, verbose_name='Master Bedroom Level')
    roommasterbedwidth = models.IntegerField(verbose_name='Master Bedroom Width')
    miscellaneous = models.CharField(max_length=765, verbose_name='Misc')
    mlsnum = models.IntegerField(verbose_name='MLS Number')
    mortgagecosold = models.CharField(max_length=75, verbose_name='Mortgage Company Sold')
    muddistrict = models.CharField(max_length=3, verbose_name='MUD District')
    parcelsmultiple = models.CharField(max_length=3, verbose_name='Multiple Parcels')
    numbarns = models.IntegerField(verbose_name='Number of Barns')
    numdiningareas = models.IntegerField(verbose_name='Number of Dining Areas')
    numlakes = models.IntegerField(verbose_name='Number of Lakes')
    numlivingareas = models.IntegerField(verbose_name='Number of Living Areas')
    numponds = models.IntegerField(verbose_name='Number of Ponds')
    numresidence = models.IntegerField(verbose_name='Number of Residence')
    numbarn1stalls = models.IntegerField(verbose_name='Number of Stalls Barn 1')
    numbarn2stalls = models.IntegerField(verbose_name='Number of Stalls Barn 2')
    numbarn3stalls = models.IntegerField(verbose_name='Number of Stalls Barn 3')
    numstocktanks = models.IntegerField(verbose_name='Number of Stock Tanks')
    numwells = models.IntegerField(verbose_name='Number of Wells')
    occupancy = models.CharField(max_length=75, verbose_name='Occupancy')
    offmarketdate = models.DateTimeField(verbose_name='Off Market Date ')
    officelist = models.CharField(max_length=75, verbose_name='Office List')
    acrespricesold = models.IntegerField(verbose_name='Old Price per Acre')
    roomother1length = models.IntegerField(verbose_name='Other Room 1 Length')
    roomother1level = models.CharField(max_length=3, verbose_name='Other Room 1 Level')
    roomother1width = models.IntegerField(verbose_name='Other Room 1 Width')
    roomother2length = models.IntegerField(verbose_name='Other Room 2 Length')
    roomother2level = models.CharField(max_length=3, verbose_name='Other Room 2 Level')
    roomother2width = models.IntegerField(verbose_name='Other Room 2 Width')
    roomother = models.CharField(max_length=765, verbose_name='Other Room Description')
    acrespasture = models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Pasture Acres')
    photocount = models.IntegerField(verbose_name='Photo Count')
    planneddevelopment = models.CharField(max_length=90, verbose_name='Planned Development')
    poolyn = models.CharField(max_length=3, verbose_name='Pool')
    pooldesc = models.CharField(max_length=765, verbose_name='Pool Description')
    possession = models.CharField(max_length=318, verbose_name='Possession')
    presentuse = models.CharField(max_length=765, verbose_name='Present Use')
    acresprice = models.IntegerField(verbose_name='Price per Acre')
    sqftprice = models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Price per SqFt.')
    proptype = models.CharField(max_length=15, verbose_name='Property Type')
    propsubtype = models.CharField(max_length=75, verbose_name='Proposed Sub Type')
    proposeduse = models.CharField(max_length=765, verbose_name='Proposed Use')
    ranchname = models.CharField(max_length=45, verbose_name='Ranch Name')
    ranchtype = models.CharField(max_length=75, verbose_name='Ranch Type')
    remarks = models.CharField(max_length=1350, verbose_name='Remarks')
    restrictions = models.CharField(max_length=765, verbose_name='Restrictions')
    roof = models.CharField(max_length=432, verbose_name='Roof')
    salesprice = models.IntegerField(verbose_name='Sales Price')
    bus1 = models.BooleanField(verbose_name='School 1 Bus')
    schoolname1 = models.CharField(max_length=96, verbose_name='School 1 Name')
    schooltype1 = models.CharField(max_length=3, verbose_name='School 1 Type')
    bus2 = models.BooleanField(verbose_name='School 2 Bus')
    schoolname2 = models.CharField(max_length=96, verbose_name='School 2 Name')
    schooltype2 = models.CharField(max_length=3, verbose_name='School 2 Type')
    bus3 = models.BooleanField(verbose_name='School 3 Bus')
    schoolname3 = models.CharField(max_length=96, verbose_name='School 3 Name')
    schooltype3 = models.CharField(max_length=3, verbose_name='School 3 Type')
    bus4 = models.BooleanField(verbose_name='School 4 Bus')
    schoolname4 = models.CharField(max_length=96, verbose_name='School 4 Name')
    schooltype4 = models.CharField(max_length=3, verbose_name='School 4 Type')
    schooldistrict = models.CharField(max_length=96, verbose_name='School District')
    security = models.CharField(max_length=3, verbose_name='Security')
    securitydesc = models.CharField(max_length=480, verbose_name='Security Description')
    showing = models.CharField(max_length=444, verbose_name='Showing')
    showinstr = models.CharField(max_length=765, verbose_name='Showing Instructions')
    soiltype = models.CharField(max_length=300, verbose_name='Soil Type')
    specialnotes = models.CharField(max_length=765, verbose_name='Special Notes')
    sqftpricecontract = models.DecimalField(decimal_places=2, max_digits=9, verbose_name='SqFt Price Contract')
    sqftsource = models.CharField(max_length=75, verbose_name='SqFt Source')
    sqfttotal = models.IntegerField(verbose_name='SqFt Total')
    state = models.CharField(max_length=6, verbose_name='State')
    statuschangedate = models.DateTimeField(verbose_name='Status Change Date')
    stories = models.IntegerField(verbose_name='Stories')
    storiesbldg = models.IntegerField(verbose_name='Stories Building')
    streetdir = models.CharField(max_length=6, verbose_name='Street Direction')
    streetnum = models.IntegerField(verbose_name='Street Number')
    streetnumdisplay = models.CharField(max_length=75, verbose_name='Street Number Display')
    streettype = models.CharField(max_length=15, verbose_name='Street Type')
    streetname = models.CharField(max_length=300, verbose_name='Streetname')
    roomstudylength = models.IntegerField(verbose_name='Study Length')
    roomstudylevel = models.CharField(max_length=3, verbose_name='Study Level')
    roomstudywidth = models.IntegerField(verbose_name='Study Width')
    style = models.CharField(max_length=765, verbose_name='Style')
    subarea = models.CharField(max_length=75, verbose_name='Sub Area')
    subdivide = models.CharField(max_length=3, verbose_name='Subdivide')
    subdivision = models.CharField(max_length=120, verbose_name='Subdivision')
    surfacerights = models.CharField(max_length=207, verbose_name='Surface Rights')
    taxid = models.CharField(max_length=90, verbose_name='Tax ID')
    taxunexempt = models.IntegerField(verbose_name='Tax Unexempt')
    thirdpartyap = models.CharField(max_length=3, verbose_name='Third Party Application')
    topography = models.CharField(max_length=396, verbose_name='Topography')
    bathstotal = models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Total Baths')
    coveredspacestotal = models.IntegerField(verbose_name='Total Covered Spaces')
    tourdate = models.DateTimeField(verbose_name='Tour Date')
    tourtime = models.CharField(max_length=75, verbose_name='Tour Time')
    unitfloornum = models.IntegerField(verbose_name='Unit Floor Number')
    unitnum = models.CharField(max_length=18, verbose_name='Unit Number')
    roomutilitywidth = models.IntegerField(verbose_name='Utiilty Room Width')
    utilities = models.CharField(max_length=1074, verbose_name='Utilities')
    utilitiesother = models.CharField(max_length=870, verbose_name='Utilities (Other)')
    roomutildesc = models.CharField(max_length=765, verbose_name='Utility Room Description')
    roomutilitylength = models.IntegerField(verbose_name='Utility Room Length')
    roomutilitylevel = models.CharField(max_length=3, verbose_name='Utility Room Level')
    yearbuilt = models.IntegerField(verbose_name='Year Built')
    yearbuiltdesc = models.CharField(max_length=75, verbose_name='Year Built Description')
    zipcode = models.CharField(max_length=75, verbose_name='Zipcode')
